[project]
name = "asteraceae"
version = "0.0.0"
description = "a BentoML-based service to run SAE-intervention"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=0.34.0",
    "bentoml @ git+https://github.com/bentoml/BentoML.git@main",
    "fastapi>=0.115.0",
    "openai>=1.47.0",
    "sae @ https://github.com/EleutherAI/sae.git@main",
    "vllm>=0.6.3; sys_platform == 'linux'",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
bentoml = { git = "https://github.com/bentoml/BentoML.git", rev = "main" }
sae = { git = "https://github.com/EleutherAI/sae.git", rev = "main" }

[tool.bentoml.build]
service = "asteraceae.service:Engine"
include = ["asteraceae/service.py"]
[tool.bentoml.build.python]
lock_packages = false
[tool.bentoml.build.docker]
python_version = "3.11"
[[tool.bentoml.build.envs]]
name = "HF_TOKEN"
[[tool.bentoml.build.envs]]
name = "HF_HUB_ENABLE_HF_TRANSFER"
value = "1"
