[project]
name = "asteraceae"
version = "0.1.0"
description = "a BentoML-based service to run SAE-intervention"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=0.34.0",
    "bentoml>=1.3.5",
    "openai>=1.47.0",
    "vllm>=0.6.1.post2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
