[tool.uv]
package = false
dev-dependencies = [
  "jupyter-client>=8.6.3",
  "jupytext>=1.16.4",
  "mypy>=1.13.0",
  "mypy-extensions>=1.0.0",
  "plotly>=5.24.1",
  "pnglatex>=1.1",
  "pre-commit>=4.2.0",
  "pylatexenc>=2.10",
  "pynvim>=0.5.0",
  "pyperclip>=1.9.0",
  "ruff>=0.6.6",
]

[tool.uv.sources]
exo.workspace = true
asteraceae.workspace = true

[tool.uv.workspace]
members = ["python/*"]

[tool.ruff]
extend-include = ["*.ipynb", "**/pyproject.toml"]
line-length = 119
indent-width = 2

[tool.ruff.format]
preview = true
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = true

[tool.ruff.lint]
preview = true
exclude = ["*.ipynb"]
ignore = ["RUF012", "ANN", "E501", "E722", "D", "E401"]
select = [
  "F",
  "D",
  "G",
  "PERF",
  "RUF",
  "W6",
  "E71",
  "E72",
  "E112",
  "E113",
  "E203",
  "E272",
  "E303",
  "E304",
  "E502",
  "E702",
  "E703",
  "E731",
  "W191",
  "W291",
  "W293",
  "UP039",
]

[tool.pyright]
include = ["python"]
exclude = ["**/node_modules", "**/__pycache__"]
useLibraryCodeForTypes = true
verboseOutput = true
enableExperimentalFeatures = true
defineConstant = { MYPY = true }
venvPath = "."
venv = ".venv"
pythonVersion = "3.11"
reportMissingImports = "warning"
reportMissingTypeStubs = false
reportPrivateUsage = "warning"
reportUnknownArgumentType = "warning"
reportUnsupportedDunderAll = "warning"
reportWildcardImportFromLibrary = "warning"

[tool.mypy]
strict = true
plugins = ['pydantic.mypy', 'mypy.plugins.attrs']
follow_imports = "silent"
ignore_missing_imports = true
check_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
