[tool.uv]
package = false
dev-dependencies = [
  "jupyter-client>=8.6.3",
  "jupytext>=1.16.4",
  "mypy>=1.13.0",
  "plotly>=5.24.1",
  "pnglatex>=1.1",
  "pylatexenc>=2.10",
  "pynvim>=0.5.0",
  "pyperclip>=1.9.0",
  "ruff>=0.6.6",
]

[tool.uv.sources]
exo.workspace = true
astaracea.workspace = true

[tool.uv.workspace]
members = ["python/*"]

[tool.ruff]
extend-include = ["*.ipynb"]
preview = true
line-length = 119
indent-width = 2

[tool.ruff.format]
preview = true
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = true

[tool.ruff.lint]
ignore = [
  "RUF012",
  "ANN",    # Mypy is better at this
  "E722",
]
select = [
  "F",
  "D",
  "G",    # flake8-logging-format
  "PERF", # perflint
  "RUF",  # Ruff-specific rules
  "W6",
  "E71",
  "E72",
  "E112",
  "E113",
  # "E124",
  "E203",
  "E272",
  # "E303",
  # "E304",
  # "E501",
  # "E502",
  "E702",
  "E703",
  "E731",
  "W191",
  "W291",
  "W293",
  "UP039", # unnecessary-class-parentheses
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
include = ["python"]
exclude = ["**/node_modules", "**/__pycache__"]
useLibraryCodeForTypes = true
verboseOutput = true
enableExperimentalFeatures = true
defineConstant = { MYPY = true }
venvPath = "."
venv = ".venv"
pythonVersion = "3.12"
reportMissingImports = "warning"
reportMissingTypeStubs = false
reportPrivateUsage = "warning"
reportUnknownArgumentType = "warning"
reportUnsupportedDunderAll = "warning"
reportWildcardImportFromLibrary = "warning"
